// Cartas originais no estilo F.D.P. — "____" marca cada lacuna.
// Para adicionar mais, é só incluir novas linhas nas listas.

const black = [
  'O que a minha avó esconde no fundo da gaveta de calcinhas? ____.',
  'O novo reality show da Globo: "No Limite do ____".',
  'Meu terapeuta disse que todos os meus problemas começaram com ____.',
  'Nunca leve ____ para um churrasco de família.',
  'O segredo de um casamento feliz é ____.',
  'O que tem no áudio de 7 minutos que o seu tio mandou no grupo da família?',
  'Fui demitido por causa de ____.',
  'A nova promoção do Méqui: compre um Big Mac e ganhe ____.',
  'O que me fez sair correndo do motel?',
  'Na minha lápide vai estar escrito: "Aqui jaz alguém que amava ____".',
  'O coach quântico garante que ____ atrai prosperidade.',
  'O que o pastor estava fazendo atrás da igreja?',
  'O pior presente de amigo secreto da firma: ____.',
  'Minha mãe me pegou com ____ e nunca mais foi a mesma.',
  'Depois de ____, nunca mais confiei em ____.',
  'O que realmente acontece no Big Brother depois que as câmeras desligam?',
  'O enredo da escola de samba campeã deste ano: "____: uma homenagem".',
  'Primeiro encontro do Tinder e ele já chegou falando de ____.',
  'O SUS agora oferece ____ de graça.',
  'Qual é o cheiro do ônibus lotado às 18h?',
  'A Anvisa acabou de proibir ____.',
  'O último livro de autoajuda mais vendido: "O Poder de ____".',
  'Meu crush me deixou no vácuo por causa de ____.',
  'Tudo que eu queria nas férias era ____ e ____.',
  'O que o síndico encontrou no lixo do 302?',
  'Plano infalível para ficar rico: passo 1, ____. Passo 2, lucro.',
  'Ninguém me avisou que a vida adulta seria basicamente ____.',
  'O que está escrito no meu histórico de pesquisa?',
  'Fui no médico e ele receitou ____ três vezes ao dia.',
  'Ganhei na Mega-Sena e a primeira coisa que comprei foi ____.',
  'O que deixou o padre sem palavras na confissão?',
  'A nova modalidade olímpica é ____.',
  'O verdadeiro motivo de o Brasil ter perdido a Copa: ____.',
  'Hoje no Fantástico: ____ assusta moradores do interior.',
  '____ é o que separa o homem dos animais.',
  'Minha mãe sempre dizia: "Filho, cuidado com ____".',
  'O que o motorista de aplicativo viu pelo retrovisor?',
  'Eu não sou alcoólatra, só gosto de ____.',
  'O novo sabor de Doritos: ____.',
  'A herança que meu avô me deixou foi ____.',
  'No fim do arco-íris não tem pote de ouro, tem ____.',
  'O que eu levaria para uma ilha deserta?',
  'Meu chefe me chamou na sala para falar sobre ____.',
  'O que causou a briga no grupo do condomínio?',
  'O tema da minha festa de 30 anos vai ser ____.',
  'Passei a noite toda ____ e acordei com ____.',
  'Em vez de pedir desculpas, o político ofereceu ____.',
  'A empresa promete: em 2030, todo brasileiro terá direito a ____.',
  'O que estava no pote de sorvete da geladeira da minha mãe?',
  'O que te faz chorar no banho?',
  'Minha mãe acha que eu sou contador, mas na verdade eu trabalho com ____.',
  'O que salvou o meu casamento?',
  'Receita de família: misture ____ com ____ e leve ao forno.',
  'Ninguém sabe, mas o Silvio Santos foi enterrado com ____.',
  'O novo emoji do WhatsApp representa ____.',
  'Não é traição se for com ____.',
  'O que não pode faltar num rolê de quinta-feira?',
  'Desculpa o atraso, eu estava ocupado com ____.',
  'O verdadeiro sentido da vida é ____.',
  'O que o cachorro trouxe de presente do quintal?',
  'Sou totalmente contra ____, mas a favor de ____.',
  'A fofoca do momento no salão de beleza: ____.',
  'O que meu pai fala quando acha que ninguém está ouvindo?',
  'A nova lei aprovada em Brasília obriga todo cidadão a ter ____.',
];

const white = [
  'Um pastor evangélico de sunga', 'O tiozão do pavê', 'Áudio de 7 minutos', 'Uma calcinha bege enorme',
  'Pagar boleto com o cartão de crédito', 'O Faustão de fio dental', 'Um peido silencioso no elevador',
  'A ex que ainda segue no Instagram', 'Cheirar a própria axila em público', 'Uma pochete cheia de farofa',
  'Arrotar o hino nacional', 'Chorar ouvindo Marília Mendonça', 'Um Uno com escada no teto',
  'Ser bloqueado pela própria mãe', 'O boy lixo', 'Um coach quântico', 'Pirâmide financeira',
  'Uma unha encravada infeccionada', 'Gemer sem querer na reunião do Zoom', 'Feijoada de ontem',
  'O ex-BBB que virou vendedor de curso', 'Pastel de vento', 'Ficar pelado no churrasco da firma',
  'Um vibrador esquecido na mala', 'A tia do zap', 'Fake news sobre vacina', 'Uma DR às 3 da manhã',
  'Gozar cedo demais', 'Lamber o chão do metrô', 'O Galvão Bueno narrando um parto',
  'Tomar banho de água fria no inverno', 'Um cocô que não desce', 'Cerveja quente', 'Sexo no carro',
  'Mandar nude no grupo errado', 'A mãe do seu melhor amigo', 'Uma espinha nas costas',
  'Calcinha comestível', 'Fingir orgasmo', 'Um Papai Noel de shopping bêbado', 'Pagode dos anos 90',
  'Morar com os pais aos 35', 'Uma maldição da cigana', 'Comer o lanche do colega na geladeira da firma',
  'Um grupo de WhatsApp só com ex', 'Ficar de recuperação em educação física', 'Chulé',
  'Cuecas furadas', 'Um velório animado', 'Dancinha do TikTok no velório', 'Um cheque sem fundo',
  'Pelos no sabonete', 'Um rato no feijão', 'A vizinha fofoqueira', 'Viagra vencido',
  'Uma tatuagem com o nome da ex', 'Ressaca de catuaba', 'Chupar limão com sal', 'O Datena gritando',
  'Votar em quem vende dentadura', 'Um bebê reborn', 'Terapia em grupo', 'Dívida no Serasa',
  'Um padre que dá em cima de todo mundo', 'Comer miojo cru', 'Dormir de calça jeans',
  'Usar meia com sandália', 'Herpes', 'Um fio de cabelo na comida', 'Um pombo comendo vômito',
  'O Ratinho fazendo xixi no balde', 'Pum na aula de yoga', 'Um sugar daddy de 80 anos',
  'A sogra morando junto', 'Um vídeo íntimo vazado', 'Rodízio de sushi de posto de gasolina',
  'Cagar no mato', 'Pegar o Uber errado', 'Esquecer o aniversário da mãe', 'Ter um trisal',
  'O cheiro de ovo cozido', 'Um DIU', 'Achar uma camisinha usada na praia', 'Jogar Free Fire aos 40 anos',
  'Um padrasto chato', 'Prisão de ventre', 'Diarreia no primeiro encontro', 'Cerveja de milho',
  'Fazer a barba das partes íntimas', 'Uma garrafa de 51 inteira', 'O horário político obrigatório',
  'Pegar piolho aos 30', 'Acordar ao lado de um desconhecido', 'Uma tia que fala "e os namoradinhos?"',
  'Uma depilação com cera quente', 'O pastor da Universal', 'Salgadinho de festa infantil',
  'Comprar seguidores', 'Ser corno', 'Um cachorro comendo a dentadura da vó', 'Ficar preso no banheiro químico',
  'Pegar Covid no Réveillon', 'Uma briga no carnaval', 'Vomitar na roda gigante', 'O peso na consciência',
  'Um curso de PNL', 'Ser trocado por um modelo do OnlyFans', 'Dívida de agiota',
  'Uma calça de oncinha', 'Um bolo de aniversário com fio de cabelo', 'Banho de cuia',
  'Pôr a culpa no cachorro', 'O primo que pede dinheiro emprestado', 'Ter que pagar pensão',
  'Uma piriguete de 70 anos', 'Meter o louco', 'Fazer xixi na piscina', 'Chorar no banho',
  'Uma mordida no mamilo', 'Tirar meleca no sinal vermelho', 'Uma fantasia de diabinha',
  'Usar o mesmo pijama há 3 dias', 'Comer o último pedaço de pizza sem perguntar', 'Bunda suada',
  'Ser expulso do grupo da família', 'Ser pego no flagra', 'Um encanador muito bem-dotado',
  'O cachorro do vizinho latindo de madrugada', 'A Xuxa', 'Silvio Santos jogando aviãozinho de dinheiro',
  'Um bilhete de amor da professora', 'Trair na Copa do Mundo', 'Dar ré no quibe', 'Mentir no currículo',
  'Ficar com o primo', 'Um cadáver no porta-malas', 'Um ménage', 'Um tapa na bunda', 'Cheiro de pé',
  'Uma bolsa falsificada da Louis Vuitton', 'Lavar a louça de má vontade', 'Pastor pedindo Pix',
  'Uma cueca freada', 'Comer areia na praia', 'Um sapo na privada', 'Gritar "Uhul!" no velório',
  'Jogar o celular na privada', 'Dar like numa foto de 2014 sem querer', 'Um peido molhado',
  'Ganhar uma meia no Natal', 'Fazer sexo com meias', 'Ficar bêbado no casamento do chefe',
  'Fingir que não viu a mensagem', 'Ter um caso com o personal trainer', 'Um bigode mal feito',
  'A cueca do Neymar', 'Ser enganado por um príncipe nigeriano', 'Um gato vomitando bola de pelo',
  'Mijar de porta aberta', 'O seu pai de sunga branca', 'Uma calvície precoce', 'Ser careca aos 25',
  'Bafo de onça', 'Engolir chiclete', 'Ser stalker do ex', 'Lamber a tampa do iogurte',
  'Comer pizza no café da manhã', 'Pornografia de bichinhos de pelúcia', 'Um tio no churrasco sem camisa',
  'Fazer cocô na casa do crush', 'Tomar um fora no altar', 'A vó jogando sinuca',
  'Uma criança gritando no avião', 'Falar com o ex bêbado', 'Pelada na rua',
  'O Tinder às 4 da manhã', 'Golpe do Pix', 'Ter 47 abas abertas', 'Um influenciador de cripto',
  'Gemidão do Zap', 'Pagar pra ver', 'Ficar de quatro', 'Um abraço por trás muito demorado',
  'Viver de brisa', 'Comer pão com Toddy', 'Um carro rebaixado com som alto', 'Usar a escova de dente do outro',
  'Um cunhado folgado', 'Ser seguido pelo ex no Spotify', 'A máfia do jogo do bicho', 'Uma rinha de galo',
  'Botox na testa', 'Silicone vazando', 'Lipo de papada', 'Ter crise de ansiedade no mercado',
  'Fumar narguilé na laje', 'Uma piscina de plástico na calçada', 'O sapato do avô',
  'Tomar Gardenal', 'Uma rave no asilo', 'Morrer de vergonha', 'O cheiro do banheiro da rodoviária',
  'Uma calcinha no ventilador', 'Pegar no sono durante o sexo', 'Ser picado por uma abelha no saco',
  'Assistir novela mexicana escondido', 'Rodar a baiana', 'Chamar a professora de "mãe"',
  'Um pinto pequeno', 'Peitinho de fora', 'Uma bunda cabeluda', 'Fazer topless na praia de Copacabana',
  'Batizar o cachorro com o nome do ex', 'A batata da perna', 'Colocar ketchup no sushi',
  'Vender a alma por um iPhone', 'O Sílvio do Zorra Total', 'Um amigo que só aparece quando precisa',
  'Comer churrasquinho de gato', 'Um palhaço triste', 'Assistir ao vivo a uma colonoscopia',
  'Perder a virgindade num Fusca', 'O fiscal da Receita Federal', 'Um ex presidiário bonzinho',
  'Uma sogra que é bruxa', 'Bater o dedinho na quina', 'Um cheiro estranho vindo da geladeira',
  'Ser o último escolhido no futebol', 'Esquecer o nome da pessoa durante o sexo',
  'O seu histórico do navegador', 'Ficar entalado na janela', 'Um padre funkeiro',
  'Um desfile de cuecas', 'Uma lap dance desastrosa', 'Comer o bolo antes do parabéns',
  'Ser processado pelo vizinho', 'Plantar bananeira pelado', 'Uma tia que vende Avon',
  'Fingir que entende de vinho', 'Pedir o Pix de volta', 'A senha do Wi-Fi do vizinho',
  'Um bafômetro', 'Um karaokê de Roberto Carlos', 'Tirar foto da comida antes de comer',
  'Uma unha postiça na sopa', 'O último gole de cerveja quente', 'Morrer abraçado com o crush',
  'Um pacote de Fandangos', 'Uma briga de bar por causa de futebol', 'Ser expulso do motel',
  'Um enterro com pagode ao vivo', 'Um mágico que faz a esposa sumir de verdade',
];

module.exports = { black, white };
